name: Hellow

on:
 workflow_dispatch: 

jobs:

  greet:
    runs-on: ubuntu-latest
    steps:
      - name: say hellow
        run: echo "Heloow dosto" 

      - name: say hellow to username
        run: echo "hellow $USER"

  details:
    runs-on: ubuntu-latest
    steps:
      - name: Version of docker and python
        run: docker --version && python --version
