name: Hellow

on:
  push:
    branches: [main]

jobs:

  greet:
    runs-on: ubuntu-latest
    steps:
      - name: say hellow
        run: echo "Heloow dosto" 

      - name: say hellow to username
        run: echo "hellow $USER"

    details:
      runs-on: ubuntu-latest
      steps:
        - name: show what is the version of Python and Docker
          run: docker --version && python --version
